### PR TITLE
dual manipulator pose goal demo

### PR DESCRIPTION
**Pull request by kruusamae**
this is intentionally undocumented demo (not mentioned in README) for the time being. i hoping you'll only review the .cpp and CMakeLists.txt file for this pull request to merge.

the demo is undocumented because it requires a different moveit_config to be set up and i am still pondering how to incorporate it with this package.

### CODE REVIEW

**Comment by kruusamae** [comment]
i forgot to mention that it is related to #6

**Review by Veix123 — APPROVED** [review]
Looks good

**Comment by kruusamae** [comment]
ping @RValner 
i'd like to merge this PR before Thursday evening ;)

**Review by RValner — APPROVED** [review]
The only thing I noticed is that you are missing the "add dependencies" in your executable targets (add_dependencies (dual_pose_goal ${catkin_EXPORTED_TARGETS}) - seems like it compiles but it's fyi that this might cause you some trouble if you integrate new features in it.

**Pull request merged**
